load data
infile '$HOME/tmp.dat' 
append into table b_cups_trans_detail
FIELDS TERMINATED BY "," TRAILING NULLCOLS
(TRANS_CODE,CHANNEL_ID,SETTLE_DATE
,SYS_TRACE,TRANS_DATE,TRANS_TIME,TRANSMIT_TIME
,CARD1_NO,CARD_TYPE,AMOUNT,FEE
,MSG_ID,PRO_CODE,CHANNEL_MCC
,CHANNEL_MERCH_ID,CHANNEL_TERM_ID,CHANNEL_RRN,AUTH_CODE
,RESP_INST_ID,ORG_SYS_TRACE,RESP_CODE,INPUT_MODE
,ISS_FEE,CHANNEL_FEE,CHANNEL_FEE2
,ORG_TRANSMIT_TIME,COND_CODE,TRAN_AREA,ISS_INST_ID
,PAY_TYPE,CHK_FLAG,ADJUST_FLAG,REMARK)
