#key: 0123456789ABCDEFFEDCBA9876543210
key: 16D0462C164CB0E3AD6EF2B0B9514092
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.21.204.1:1521:POSP
    #url: jdbc:oracle:thin:@10.255.0.144:1521:pandb
    username: posp
    password: SMjeNA0heeW*Hy8$
    #password: posp
    initialSize: 1
    minIdle: 1
    maxActive: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  jpa:
    show-sql: false
  hibernate:
    ddl-auto: none
  jackson:
    serialization.indent-output: true
  application:
    name: transnoticejava
  profiles:
        active: prod
logging:
  level: info
  mapper: info
  path: /home/posp/log

threadpoolnum: 3
postranscode: 024100','024103','024102','024123','020001','U20000','020000','020003','020002','020023','M20000','M20003','M20002','M20023','M20010','M20013','M20012','T20000','T20003
inlinetranscode: 02W600','02B600','0AB600','0AW600','02Y100','02Y200','02W100','02W200','02B100','02B200','0AW100','0AW200','0AB100','0AB200','02Y600','0AY200','0AQ000